[programs.localnet]
anchor_blog = "HkUTPinS5eZotWjoTqDpHWxXrcZqSfn79uQQgmTL5uxg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/grantfindlay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
